languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Rajesh Kanna V"
# copyright = "Rajesh Kanna V"

[params]
  dateFormat = "2 January 2006"

  description = "Personal website of Rajesh Kanna V"

[params.author]
  name = "Rajesh Kanna V"
  image = "img/RajeshProfile1.jpg"
  headline = "Data Scientist, AI Engineer"
  bio = "Data Scientist, AI Engineer."
  links = [
    { instagram = "https://instagram.com/iBelieve6580" },
    { github = "https://github.com/vrajeshtrichy" },
    { linkedin = "https://www.linkedin.com/in/vrajeshtrichy/" },
  ]